### ISSUE TITLE
🐞[BUG] Link to claim stacking reward tx incorrect

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin-ui#109]
**Describe the bug**
The message and link of the claim stacking reward transaction show "User registered successfully" and the link is https://minecitycoins.com/mia/stacking?chain=testnet

**To Reproduce**
1. Go to 'https://minecitycoins.com/mia/stacking?chain=mainnet'
2. Click on 'Claim Rewards'
3. See error

**Screenshots**

![Screenshot from 2021-11-10 22-17-54](https://user-images.githubusercontent.com/1449049/141195251-8303daa2-3f18-41bd-864f-2bb9b2ca8990.png)

**Comment by whoabuddy** [comment]
Yep, can confirm it's the wrong message here, thanks for flagging!

https://github.com/citycoins/citycoin-ui/blob/4d5a34eb4a249e6618332171ae4b429be00ebfa3/src/components/stacking/StackingReward.js#L115-L122

For the txid link, that comes from here, I'll have to debug and see what happened. It should be the url plus selected chain.

https://github.com/citycoins/citycoin-ui/blob/4d5a34eb4a249e6618332171ae4b429be00ebfa3/src/components/common/LinkTx.js#L6-7

Surprised nobody else has seen this with other transactions that use the same component for responses. Good catch.

**Comment by friedger** [comment]
Similar for mining transaction, the link is incorrect
![Screenshot from 2021-11-11 17-11-14](https://user-images.githubusercontent.com/1449049/141331012-0557f318-4be7-4056-b32e-eda9d865b9c1.png)

**Comment by whoabuddy** [comment]
It should be fixed across the board (same component used in all) by the open PR.
