### ISSUE TITLE
🐞[BUG] My swaps don't show up in the UI

### ISSUE THREAD

**Issue by kevinpCroat** [citycoins/citycoin-ui#118]
**Describe the bug**
I don't see my swaps in the swaps section.

**To Reproduce**
1. Do a swap
2. Connect w Hiro Web Wallet
3. View profile -> https://www.catamaranswaps.org/#offcanvasProfile

**Expected behavior**
Display my completed swaps. 

**Desktop (please complete the following information):**
 - Browser: Brave

**Comment by whoabuddy** [comment]
Hi @kevinpCroat - this repo is for the https://minecitycoins.com interface, please file this issue in the Catamaran Swaps repo (linked below).

https://github.com/friedger/stacks-swaps
