### ISSUE TITLE
Notice This transaction would have succeeded, but was rolled back by a supplied post-condition. ⚡[FEAT] 

### ISSUE THREAD

**Issue by Elyalfa** [citycoins/citycoin-ui#169]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Palenyj1981** [comment]
I didn't do any of the above.  thank you

ср, 22 лист. 2023, 20:47 користувач Ely Alfaro ***@***.***>
пише:

**Comment by whoabuddy** [comment]
Closing out as it's just an issue template.
