### ISSUE TITLE
Notice This transaction would have succeeded, but was rolled back by a supplied post-condition.🐞[BUG] 

### ISSUE THREAD

**Issue by Elyalfa** [citycoins/citycoin-ui#170]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eric-hendrickson** [comment]
Appears to be a duplicate of #167

**Comment by whoabuddy** [comment]
Closing out as it's just an issue template.
