### ISSUE TITLE
Activating registration does not change "not yet activated" message

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin-ui#18]
The text "City Coin is not activated" should disappear after mining registration is complete.

![image](https://user-images.githubusercontent.com/9038904/121440809-40662480-c94e-11eb-8b3c-6f3e3f3a48c3.png)

**Comment by friedger** [comment]
It shows after the activation delay

**Comment by friedger** [comment]
See also #11

**Comment by whoabuddy** [comment]
Closing in favor of #11
