### ISSUE TITLE
Mining Claim: pending rewards should not be displayed

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin-ui#22]
Under claim mining rewards I saw that I won a block (or at least I think I did?):

![image](https://user-images.githubusercontent.com/9038904/121535332-ae9afd80-c9c7-11eb-81b1-d409c2d34625.png)

I then tried claiming it using the displayed block height, tx confirmed here:

https://explorer.stacks.co/txid/0x51ed3566dce576fe56c02a6709a90e47e3003442266f5fff53681ac0277983c1?chain=testnet

After refreshing now I see the same message and it's not easy to tell if I should claim for that height again or not.

If we could update it to be a button per claim like the screenshot below, it would prevent users from having to enter the block number, and also make it easier to see if a reward was claimed or not.

![Screenshot_from_2021-06-03_21-09-06](https://user-images.githubusercontent.com/9038904/121535926-384acb00-c9c8-11eb-8cda-ca3719152995.png)

**Comment by Michel-Leideson** [comment]
I went through this experience after claiming a certain amount of blocks, so I didn't know what the next claim would be, so I needed to analyze transaction by transaction. So I understand that we need to have a different interaction when receiving the reward.
![image](https://user-images.githubusercontent.com/83844412/123140942-3ce29b00-d42e-11eb-8eda-eeb87bb26afb.png)

**Comment by whoabuddy** [comment]
I dug into this a little more, the "Pending tx" bit actually means the token reward maturity window (100 blocks) has not passed yet - so we don't know the winner and if we should have a claim button or not. I'm thinking these should be hidden to cause less confusion.

**Comment by Michel-Leideson** [comment]
Strange, this means that even without having passed the maturity time, I was able to complain by typing the block number in the search field.
![image](https://user-images.githubusercontent.com/83844412/123182837-a1215100-d466-11eb-9059-29a60bbe0bb6.png)

**Comment by whoabuddy** [comment]
That form at the bottom will be phased out for a claim button related to each entry, see #54 

We definitely need to handle the state better here. Right now there's no easy way to see the current testnet block height outside of going to [the explorer](https://explorer.stacks.co/?chain=testnet) right now - which is documented as something to add in #49

If you claim within the 100 block maturity window it definitely fails, though, do you have a link to the TX in the explorer for those transactions? That would be really helpful.
