### ISSUE TITLE
Lost mining blocks shown as empty lines

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin-ui#25]
Lost blocks are shown as empty lines or as claimed (was claimed by other miner)

![Screenshot from 2021-06-11 09-35-36](https://user-images.githubusercontent.com/1449049/121649150-8fb86c00-ca98-11eb-96b4-62fb26925307.png)

**Comment by whoabuddy** [comment]
Is this still relevant in the latest design? I am not seeing any pending claims in each of my profiles.

**Comment by friedger** [comment]
still relevant because nothing is shown for the list item if lost:

![Screenshot from 2021-06-22 14-05-06](https://user-images.githubusercontent.com/1449049/122921530-e197a680-d362-11eb-9e42-137770ed76a7.png)
