### ISSUE TITLE
Do not show claim txs in recent activities

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin-ui#26]
Is it interesting whether mining rewards have been claimed?

**Comment by whoabuddy** [comment]
In #31 I moved the recent TXs to a dashboard page, so it would make sense to show all TXs in a block, for mining/stacking/claiming etc. It also has an accordion layout that needs some modification, but should make it easier to display and navigate the transactions in each block.

**Comment by whoabuddy** [comment]
Closing this out in favor of #35, #37 and #39
