### ISSUE TITLE
Current stx committed

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin-ui#28]
Current stx committed is shown as 0 even though miners send stx.
![Screenshot from 2021-06-11 10-23-18](https://user-images.githubusercontent.com/1449049/121655808-2d169e80-ca9f-11eb-9ec1-371d520cfbcc.png)

**Comment by whoabuddy** [comment]
This was a misunderstanding of which reward cycle was active, cycle 4 did not have stacking active, so 100% of STX sent to contract was going to the city wallet.

Cycle 5 did show some values based on mining over 30 blocks, and data appears to be updating now when stacking is active.
