### ISSUE TITLE
Add sign out functionality to full profile component

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin-ui#34]
There is a button for signing out, but it doesn't do anything yet!

![image](https://user-images.githubusercontent.com/9038904/122792932-79b46380-d26f-11eb-98df-194f21f19145.png)

**Comment by mindninjaX** [comment]
Hi @whoabuddy! I would like to work on this. I can help with this issue.

**Comment by whoabuddy** [comment]
Hi @mindninjaX! Awesome, happy to have your help! Please send a PR with the changes and we'll get them added.

**Comment by mindninjaX** [comment]
Thanks! I'll start working right away 🔥

**Comment by whoabuddy** [comment]
Hey @mindninjaX - sorry but this one got closed out as part of a bigger PR. If there are any other issues that catch your eye we appreciate the help!

**Comment by mindninjaX** [comment]
No problem @whoabuddy! I'll look for other issues... Also always let me know if you have new **good-first-issue** :D
