### ISSUE TITLE
Dashboard: make information more accessible / useful

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin-ui#37]
Right now I wired up the dashboard to show PoX stats from the contract as well as an activity log (thanks to @friedger adding the `CityCoinTxList` component).

The layout is a little messy, and it should be easier to read and understand what information is being presented.

Are there other things we should display here? What is most useful to the user?

Should the information be split into relevant tabs, e.g. mining stats like #13 displayed on the mining tab?

**Comment by friedger** [comment]
Thing to display: How much is in the city treasury

In general, the dashboard is a technical page, isn't it?
It could be more informational like stacking club. How far are we into the current cycle, how many miners, etc.

**Comment by whoabuddy** [comment]
That's a good idea, it'd also be good to know the current stacks block, and some info may be relevant per tab rather than on the dashboard, i.e. when on mining tab knowing the current block height compared to last mining TX can tell you if you should submit another TX or wait to avoid getting an error, or on the stacking tab knowing how much you locked and when the reward cycles end.

I think it's worth making a list of what info is useful where and we can ask testers to provide input once we get more people looking at it.

**Comment by whoabuddy** [comment]
Add ratio of total supply to total locked citycoins for Stacking per @314159265359879 recommendation
