### ISSUE TITLE
🐞[BUG] activity log accordion is broken

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin-ui#38]
The accordion used to display the activity log is broken.

The naming for each item uses the same IDs for each entry, so they all expand/contract at the same time.

In the `CityCoinTxList` component, the key used for iterating over the `blockHeights` array should set the following values for each component it creates, rather than just reuse the same `One` for all:

```
<h2 class="accordion-header" id="accordionActivityLog-headingOne">
data-bs-target="#accordionActivityLog-activityOne"
aria-controls="accordionActivityLog-activityOne"
id="accordionActivityLog-activityOne"
aria-labelledby="accordionActivityLog-headingOne"
```

As part of #31 I added [number-to-words](https://github.com/OmgImAlexis/number-to-words) as a dependency, which should make it easy to take the key and convert it into the relevant IDs and values. e.g. below:

```
import converter from 'number-to-words';

converter.toWords(13); // => “thirteen”
```

**Comment by friedger** [comment]
I like the fact that I don't have to open each block

**Comment by whoabuddy** [comment]
Makes sense, we can make them work individually and add a show all button too - that way it's up to the user. I'd like to expand the info on each card too since we know mobile isn't supported right now we can take advantage of the real estate. For now I think it's a good start though!
