### ISSUE TITLE
🐞[BUG] Using _blank without referrer

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin-ui#42]
**Describe the bug**
 Using target="_blank" without rel="noreferrer" is a security risk: see https://html.spec.whatwg.org/multipage/links.html#link-type-noopener

**Comment by whoabuddy** [comment]
Agreed, that'd be a mistake on my part - good catch!

I was using `noopener` in some spots when linking to the explorer or other Stacks sites.
