### ISSUE TITLE
🐞[BUG] claim-stacking-reward fails due to post conditions

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin-ui#47]
**Describe the bug**

When trying to claim tokens at a specific block height through the function `claim-stacking-reward` in the contract, the transaction succeeds but then is rolled back by a post-condition.

[Example TX linked here](https://explorer.stacks.co/txid/0xf20f8384b6807beb174c70ecfbaaed8d7c00cf78ba83c29fa0838cb15fd72f26?chain=testnet)

**To Reproduce**

1. Go to https://testnet.minemiamicoin.com
2. Mine some CityCoins
3. Claim some CityCoins
4. Stack some CityCoins
5. Claim the stacking reward

**Expected behavior**

Both STX and CityCoins should have transferred to my wallet.

**Additional Context**

Relevant contract code below:

```
(define-public (claim-stacking-reward (target-reward-cycle uint))
  (let (
    (stacker tx-sender)  
    (entitled-ustx (get-entitled-stacking-reward tx-sender target-reward-cycle block-height))
    (stacked-in-cycle (get-stacked-in-cycle tx-sender target-reward-cycle))
  )
  (begin
    (asserts! (> entitled-ustx u0)
      (err ERR-NOTHING-TO-REDEEM))
    (map-set stacked-per-cycle
      { stacker: tx-sender, reward-cycle: target-reward-cycle }
      { amount-token: u0 })
    (try! (as-contract (stx-transfer? entitled-ustx tx-sender stacker)))
    (try! (as-contract (ft-transfer? citycoins stacked-in-cycle tx-sender stacker)))
    (ok true)
  ))
)
```

Noting that there are some differences in the token code between the [version deployed to testnet](https://explorer.stacks.co/txid/ST3CK642B6119EVC6CT550PW5EZZ1AJW6608HK60A.comfortable-purple-kiwi?chain=testnet) and the most recent code in [the citycoins repo](https://github.com/citycoins/citycoin/issues/83).

**Comment by aulneau** [comment]
That transaction has no post-conditions, anytime there are asset transfers and the post condition mode is set to DENY, you need to explicitly define the assets, participant, and amounts to be transferred.

**Comment by whoabuddy** [comment]
Working on a fix for this and will submit a PR today!
