### ISSUE TITLE
⚡[FEAT] display more info on stacking tab

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin-ui#50]
A few things that would be helpful:

- display current stacking cycle, including start and end height
- display target stacking cycle (generally the *next* one from tx submission)

**Comment by kurtgrela** [comment]
Also, display how long is 1 reward cycle.  Then estimate how long 32 cycles is.

I see the answer in the docs.  However, having it on the tab would be helpful.

Reward cycles are 2,100 Stacks blocks in length (about two weeks), similar to Stacking STX.

32 cycles is about 64 weeks?!  that's longer than I expected.
