### ISSUE TITLE
Develop Web UI for Mining and Stacking

### ISSUE THREAD

**Issue by asteriabtc** [citycoins/citycoin-ui#7]
Initial list of criteria based on [PRD](https://github.com/citycoins/citycoin/blob/main/citycoin-prd.md) below:

- [x] a miner can submit STX to the contract using the Stacks Web Wallet
- [x] a miner can choose to submit for one or multiple blocks at a given rate
- [x] a miner can see available citycoin rewards and claim them
- [x] a miner can see their mining history, stored in Gaia (TBF)
- [x] a Stacker can submit citycoin to the contract using the Stacks Web Wallet
- [x] a Stacker can choose the number of reward cycles to participate in
- [x] a Stacker can see available STX rewards and claim them
- [x] a Stacker can see their Stacking history, stored in Gaia (TBF)

General UI flow outlined here:
https://miro.com/app/board/o9J_lGTdbbg=/?moveToWidget=3074457358599766193&cot=14

**Comment by whoabuddy** [comment]
Closing this as the basic components are in place, will open new issues for what doesn't work yet.
