### ISSUE TITLE
🐞[BUG] View address on explorer results in 404

### ISSUE THREAD

**Issue by anibalbosco** [citycoins/citycoin-ui#74]
**Describe the bug**
Can't 'View address on explorer' after logging in to 'https://minecitycoins.com'

**To Reproduce**
1. Go to 'https://minecitycoins.com/'
2. Click on 'Profile'
3. Click on 'Actions'
4. Click on 'View address on explorer'
5. Get error 'This address doesn't seem correct. This page isn't available, and it looks like the address provided isn't correct.'

**Expected behavior**
View my address in explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/86413500/130362430-a2000ebb-2d53-4bf5-b3fa-7b4380eb4395.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [chrome]

**Additional context**
Tried this after logging in with wallet SP2T04RQY3SP5V24233ABVX9G5CV14NMSB1ZF83NQ

Sometimes, instead of the word 'profile', it has part of my address, but most of the time it just says 'profile', am I really logged in?
![image](https://user-images.githubusercontent.com/86413500/130362543-c5ba3b9f-de4c-48a5-8a32-062f172bf7b5.png)

**Comment by whoabuddy** [comment]
This is related to #33 - the profile component isn't updating correctly, so the link goes to `undefined` versus the actual STX address.

Will leave this open to address it, though, thanks for the report! Can you confirm if it works correctly after a refresh?
