### ISSUE TITLE
⚡[FEAT] Show which coin the user is looking at

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin-ui#82]
**Is your feature request related to a problem? Please describe.**
The UI does not really show that it showing details of and using MIA coin contract.

**Describe the solution you'd like**
Redirect `/` to `/mia`. Use the coin symbol as parameter for all components.

**Describe alternatives you've considered**
Hardcode the coin symbol.

**Additional context**
Future coins can be supported more easily with this feature.

**Comment by whoabuddy** [comment]
I like this idea, there are some constants that could be stored per CityCoin, and it would go along nicely with #84 as well as other small issues about displaying contract-specific data.

The landing page could be altered to show a logo of each CityCoin, and selecting one would route you to the path for that coin and related constants, components, etc. It makes sense to me to start small with the necessary data, then slowly expand this to be more feature-rich.
