### ISSUE TITLE
⚡[FEAT] Loading spinner could accept text

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin-ui#97]
**Is your feature request related to a problem? Please describe.**

Not a problem, more of an efficiency thing. We moved from the text `Loading...` to spinners, but sometimes having text withthe spinner is nice to help clarify *what* is loading.

**Describe the solution you'd like**

The LoadingSpinner component could accept an optional text value, and display it with the spinner.

**Comment by abdullahranginwala** [comment]
I would like to take this up!

**Comment by whoabuddy** [comment]
Awesome, thanks @abdullahranginwala!

Feel free to submit a PR linked to this issue and if you have any questions, let me know!

**Comment by abdullahranginwala** [comment]
@whoabuddy Thank you, I am super excited for this opportunity. I have made the necessary changes but it is unclear what you mean by 'optional text'

**Comment by whoabuddy** [comment]
Happy you are enjoying it! Where did you make the changes? Are you going to submit a pull request?

As far as the "optional text", I mean if I pass in text as a prop to the component, it should render it, otherwise it should just load the spinner if not.

Here is an example of a FormResponse component that accepts a txId, but doesn't show anything if it's blank:

https://github.com/citycoins/citycoin-ui/blob/fix/launch-updates/src/components/common/FormResponse.js

Then when it's called, you either pass the info or a blank value:

https://github.com/citycoins/citycoin-ui/blob/fix/launch-updates/src/components/mining/MineCityCoins.js#L355-L360

(this comes from a WIP branch, but outlines the general idea)

**Comment by whoabuddy** [comment]
Fixed in #107
